package love.marblegate.flowingagony.config;

import net.minecraftforge.common.ForgeConfigSpec;

public class Config {
    public static ForgeConfigSpec ACT_CONFIG;
    public static ForgeConfigSpec.BooleanValue AN_ENCHANTED_GOLDEN_APPLE_A_DAY;
    public static ForgeConfigSpec.BooleanValue DEATH_PUNK;
    public static ForgeConfigSpec.BooleanValue EXOTIC_HEALER;
    public static ForgeConfigSpec.BooleanValue SAVOR_THE_TASTED;
    public static ForgeConfigSpec.BooleanValue TRICKSTER;
    public static ForgeConfigSpec.BooleanValue COVERT_KNIFE;
    public static ForgeConfigSpec.BooleanValue ENCIOUS_KIND;
    public static ForgeConfigSpec.BooleanValue EYESORE;
    public static ForgeConfigSpec.BooleanValue SOURCE_OF_ENVY;
    public static ForgeConfigSpec.BooleanValue THORN_IN_FLESH;
    public static ForgeConfigSpec.BooleanValue CLEANSING_BEFORE_USING;
    public static ForgeConfigSpec.BooleanValue COME_BACK_AT_DUSK;
    public static ForgeConfigSpec.BooleanValue DIRTY_MONEY;
    public static ForgeConfigSpec.BooleanValue PILFERAGE_CREED;
    public static ForgeConfigSpec.BooleanValue REGULAR_CUSTOMER_PROGRAM;
    public static ForgeConfigSpec.BooleanValue ARMOR_UP;
    public static ForgeConfigSpec.BooleanValue FRIVOLOUS_STEP;
    public static ForgeConfigSpec.BooleanValue MIRACULOUS_ESCAPE;
    public static ForgeConfigSpec.BooleanValue POTENTIAL_BURST;
    public static ForgeConfigSpec.BooleanValue STUBBORN_STEP;
    public static ForgeConfigSpec.BooleanValue INFECTIOUS_MALICE;
    public static ForgeConfigSpec.BooleanValue I_SEE_YOU_NOW;
    public static ForgeConfigSpec.BooleanValue MALICE_OUTBREAK;
    public static ForgeConfigSpec.BooleanValue PERCEIVED_MALICE;
    public static ForgeConfigSpec.BooleanValue VENGEANCE;
    public static ForgeConfigSpec.BooleanValue AGONY_SCREAMER;
    public static ForgeConfigSpec.BooleanValue CUTTING_WATERMELON_DREAM;
    public static ForgeConfigSpec.BooleanValue INSANE_POET;
    public static ForgeConfigSpec.BooleanValue PAPER_BRAIN;
    public static ForgeConfigSpec.BooleanValue SHOCK_THERAPY;
    public static ForgeConfigSpec.BooleanValue BURNING_PHOBIA;
    public static ForgeConfigSpec.BooleanValue CONSTRAINED_HEART;
    public static ForgeConfigSpec.BooleanValue DROWNING_PHOBIA;
    public static ForgeConfigSpec.BooleanValue PIERCING_FEVER;
    public static ForgeConfigSpec.BooleanValue PRAYER_OF_PAIN;
    public static ForgeConfigSpec.BooleanValue FRESH_REVENGE;
    public static ForgeConfigSpec.BooleanValue HATRED_BLOODLINE;
    public static ForgeConfigSpec.BooleanValue OUTRAGEOUS_SPIRIT;
    public static ForgeConfigSpec.BooleanValue RESENTFUL_SOUL;
    public static ForgeConfigSpec.BooleanValue TOO_RESENTFUL_TO_DIE;
    public static ForgeConfigSpec.BooleanValue MORIRS_DEATHWISH;
    public static ForgeConfigSpec.BooleanValue MORIRS_LIFEBOUND;
    public static ForgeConfigSpec.BooleanValue NECESSARY_EVIL;
    public static ForgeConfigSpec.BooleanValue SURVIVAL_RUSE;
    public static ForgeConfigSpec.BooleanValue SURVIVAL_SHORTCUT;
    public static ForgeConfigSpec.BooleanValue CORRUPTED_KINDRED;
    public static ForgeConfigSpec.BooleanValue LIGHTBURN_FUNGAL_PARASITIC;
    public static ForgeConfigSpec.BooleanValue PROTOTYPE_CHAOTIC;
    public static ForgeConfigSpec.BooleanValue PROTOTYPE_CHAOTIC_TYPE_BETA;
    public static ForgeConfigSpec.BooleanValue SHADOWBORN;
    public static ForgeConfigSpec.BooleanValue BURIAL_OBJECT;

    static{
        ForgeConfigSpec.Builder ACT_BUILDER = new ForgeConfigSpec.Builder();
        ACT_BUILDER.comment("Enchantment Acquirable Setting").push("general");

        AN_ENCHANTED_GOLDEN_APPLE_A_DAY = ACT_BUILDER.comment("An Enchanted Golden Apple A Day").define("acquirable",true);
        DEATH_PUNK = ACT_BUILDER.comment("Deathpunk").define("acquirable",true);
        EXOTIC_HEALER = ACT_BUILDER.comment("Exotic Healer").define("acquirable",true);
        SAVOR_THE_TASTED = ACT_BUILDER.comment("Savor the Tasted").define("acquirable",true);
        TRICKSTER = ACT_BUILDER.comment("Trickster").define("acquirable",true);
        COVERT_KNIFE = ACT_BUILDER.comment("Covert Knife").define("acquirable",true);
        ENCIOUS_KIND = ACT_BUILDER.comment("Envious Kind").define("acquirable",true);
        EYESORE = ACT_BUILDER.comment("Eyesore").define("acquirable",true);
        SOURCE_OF_ENVY = ACT_BUILDER.comment("Source of Envy").define("acquirable",true);
        THORN_IN_FLESH = ACT_BUILDER.comment("Thorn in Flesh").define("acquirable",true);
        CLEANSING_BEFORE_USING = ACT_BUILDER.comment("Cleansing Before Using").define("acquirable",true);
        COME_BACK_AT_DUSK = ACT_BUILDER.comment("Come Back At Dusk").define("acquirable",true);
        DIRTY_MONEY = ACT_BUILDER.comment("Dirty Money").define("acquirable",true);
        PILFERAGE_CREED = ACT_BUILDER.comment("Pilferage Creed").define("acquirable",true);
        REGULAR_CUSTOMER_PROGRAM = ACT_BUILDER.comment("Regular Customer Program").define("acquirable",true);
        ARMOR_UP = ACT_BUILDER.comment("Armor Up!").define("acquirable",true);
        FRIVOLOUS_STEP = ACT_BUILDER.comment("Frivolous Step").define("acquirable",true);
        MIRACULOUS_ESCAPE = ACT_BUILDER.comment("Miraculous Escape").define("acquirable",true);
        POTENTIAL_BURST = ACT_BUILDER.comment("Potential Burst").define("acquirable",true);
        STUBBORN_STEP = ACT_BUILDER.comment("Stubborn Step").define("acquirable",true);
        INFECTIOUS_MALICE = ACT_BUILDER.comment("Infectious Malice").define("acquirable",true);
        I_SEE_YOU_NOW = ACT_BUILDER.comment("I See You Now").define("acquirable",true);
        MALICE_OUTBREAK = ACT_BUILDER.comment("Malice OutBreak").define("acquirable",true);
        PERCEIVED_MALICE = ACT_BUILDER.comment("Perceived Malice").define("acquirable",true);
        VENGEANCE = ACT_BUILDER.comment("Vengeance").define("acquirable",true);
        AGONY_SCREAMER = ACT_BUILDER.comment("Agony Screamer").define("acquirable",true);
        CUTTING_WATERMELON_DREAM = ACT_BUILDER.comment("Cutting Watermelon Dream").define("acquirable",true);
        INSANE_POET = ACT_BUILDER.comment("Insane Poet").define("acquirable",true);
        PAPER_BRAIN = ACT_BUILDER.comment("Paper Brain").define("acquirable",true);
        SHOCK_THERAPY = ACT_BUILDER.comment("Shock Therapy").define("acquirable",true);
        BURNING_PHOBIA = ACT_BUILDER.comment("Burning Phobia").define("acquirable",true);
        CONSTRAINED_HEART = ACT_BUILDER.comment("Constrained Heart").define("acquirable",true);
        DROWNING_PHOBIA = ACT_BUILDER.comment("Drowning Phobia").define("acquirable",true);
        PIERCING_FEVER = ACT_BUILDER.comment("Piercing Fever").define("acquirable",true);
        PRAYER_OF_PAIN = ACT_BUILDER.comment("Prayer of Pain").define("acquirable",true);
        FRESH_REVENGE = ACT_BUILDER.comment("Fresh Revenge").define("acquirable",true);
        HATRED_BLOODLINE = ACT_BUILDER.comment("Hatred Bloodline").define("acquirable",true);
        OUTRAGEOUS_SPIRIT = ACT_BUILDER.comment("Outrageous Spirit").define("acquirable",true);
        RESENTFUL_SOUL = ACT_BUILDER.comment("Resentful Soul").define("acquirable",true);
        TOO_RESENTFUL_TO_DIE = ACT_BUILDER.comment("Too Resentful to Die").define("acquirable",true);
        MORIRS_DEATHWISH = ACT_BUILDER.comment("Morir's Deathwish").define("acquirable",true);
        MORIRS_LIFEBOUND = ACT_BUILDER.comment("Morir's Lifebound").define("acquirable",true);
        NECESSARY_EVIL = ACT_BUILDER.comment("Necessary Evil").define("acquirable",true);
        SURVIVAL_RUSE = ACT_BUILDER.comment("Survival Ruse").define("acquirable",true);
        SURVIVAL_SHORTCUT = ACT_BUILDER.comment("Survival Shortcut").define("acquirable",true);
        CORRUPTED_KINDRED = ACT_BUILDER.comment("Corrupted Kindred").define("acquirable",true);
        LIGHTBURN_FUNGAL_PARASITIC = ACT_BUILDER.comment("Lightburn Fungal Parasitic").define("acquirable",true);
        PROTOTYPE_CHAOTIC = ACT_BUILDER.comment("Prototype Chaotic").define("acquirable",true);
        PROTOTYPE_CHAOTIC_TYPE_BETA = ACT_BUILDER.comment("Prototype Chaotic Type β").define("acquirable",true);
        SHADOWBORN = ACT_BUILDER.comment("Shadowburn").define("acquirable",true);
        BURIAL_OBJECT = ACT_BUILDER.comment("Burial Object").define("acquirable",true);

        ACT_BUILDER.pop();
        ACT_CONFIG = ACT_BUILDER.build();
    }
}
